In [1]:
# NLP LAB - TEXT PREPROCESSING AND N-GRAM ANALYSIS

import nltk
import string
import re
import pandas as pd

from nltk.corpus import brown, stopwords, words
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.util import ngrams
from nltk.probability import FreqDist
from difflib import get_close_matches

# Download required NLTK resources
resources = [
    'brown',
    'punkt',
    'punkt_tab',
    'stopwords',
    'wordnet',
    'omw-1.4',
    'words'
]

for resource in resources:
    nltk.download(resource, quiet=True)

print("All required libraries and NLTK resources are ready.")

All required libraries and NLTK resources are ready.

In [2]:
# Q1(a): Load Brown Corpus and select at least 20 sentences

brown_sentences = brown.sents()[:20]

# Convert word lists into sentences
sentences = [' '.join(sentence) for sentence in brown_sentences]

print("Total sentences selected:", len(sentences))

print("\nOriginal Brown Corpus Sentences:\n")

for i, sentence in enumerate(sentences[:10], 1):
    print(f"{i}. {sentence}")

Total sentences selected: 20

Original Brown Corpus Sentences:

1. The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .
2. The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .
3. The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .
4. `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .
5. The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .
6. It recommended that Fulton legislators act `` to have these laws studied and revised to the end of modernizing and improving them '' .
7. The grand jury commented on a number of other topics , among them the Atlanta and Fulton County purchasing departments which it said `` are well operated and follow generally accepted practices which inure to the best interest of both governments '' .
8. Merger proposed
9. However , the jury said it believes `` these two offices should be combined to achieve greater efficiency and reduce the cost of administration '' .
10. The City Purchasing Department , the jury said , `` is lacking in experienced clerical personnel as a result of city personnel policies '' .

In [3]:
# Q1(b): Perform sentence-level and word-level tokenization

# Combine selected sentences into one text
text = ' '.join(sentences)

# Sentence tokenization
sentence_tokens = sent_tokenize(text)

print("Sentence Tokenization:\n")

for i, sentence in enumerate(sentence_tokens[:5], 1):
    print(f"{i}. {sentence}")

# Word tokenization
word_tokens = [word_tokenize(sentence) for sentence in sentence_tokens]

print("\nWord Tokenization:\n")

for i, tokens in enumerate(word_tokens[:5], 1):
    print(f"Sentence {i}: {tokens}")

Sentence Tokenization:

1. The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .
2. The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .
3. The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .
4. `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .
5. The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .

Word Tokenization:

Sentence 1: ['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', 'Atlanta', "'s", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', '``', 'that', 'any', 'irregularities', 'took', 'place', '.']
Sentence 2: ['The', 'jury', 'further', 'said', 'in', 'term-end', 'presentments', 'that', 'the', 'City', 'Executive', 'Committee', ',', 'which', 'had', 'over-all', 'charge', 'of', 'the', 'election', ',', '``', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'City', 'of', 'Atlanta', '``', 'for', 'the', 'manner', 'in', 'which', 'the', 'election', 'was', 'conducted', '.']
Sentence 3: ['The', 'September-October', 'term', 'jury', 'had', 'been', 'charged', 'by', 'Fulton', 'Superior', 'Court', 'Judge', 'Durwood', 'Pye', 'to', 'investigate', 'reports', 'of', 'possible', '``', 'irregularities', '``', 'in', 'the', 'hard-fought', 'primary', 'which', 'was', 'won', 'by', 'Mayor-nominate', 'Ivan', 'Allen', 'Jr.', '.']
Sentence 4: ['``', 'Only', 'a', 'relative', 'handful', 'of', 'such', 'reports', 'was', 'received', '``', ',', 'the', 'jury', 'said', ',', '``', 'considering', 'the', 'widespread', 'interest', 'in', 'the', 'election', ',', 'the', 'number', 'of', 'voters', 'and', 'the', 'size', 'of', 'this', 'city', '``', '.']
Sentence 5: ['The', 'jury', 'said', 'it', 'did', 'find', 'that', 'many', 'of', 'Georgia', "'s", 'registration', 'and', 'election', 'laws', '``', 'are', 'outmoded', 'or', 'inadequate', 'and', 'often', 'ambiguous', '``', '.']

In [4]:
# Q1(c) and Q1(d):
# Convert tokens to lowercase
# Remove punctuation
# Remove English stop words

stop_words = set(stopwords.words('english'))

# Convert to lowercase
lower_tokens = [
    [word.lower() for word in sentence]
    for sentence in word_tokens
]

# Remove punctuation and stop words
cleaned_tokens = [
    [
        word for word in sentence
        if word.isalpha() and word not in stop_words
    ]
    for sentence in lower_tokens
]

print("Lowercase and cleaned tokens:\n")

for i in range(5):
    print(f"\nSentence {i+1}")
    print("Lowercase:", lower_tokens[i])
    print("Cleaned  :", cleaned_tokens[i])

Lowercase and cleaned tokens:


Sentence 1
Lowercase: ['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'atlanta', "'s", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', '``', 'that', 'any', 'irregularities', 'took', 'place', '.']
Cleaned  : ['fulton', 'county', 'grand', 'jury', 'said', 'friday', 'investigation', 'atlanta', 'recent', 'primary', 'election', 'produced', 'evidence', 'irregularities', 'took', 'place']

Sentence 2
Lowercase: ['the', 'jury', 'further', 'said', 'in', 'term-end', 'presentments', 'that', 'the', 'city', 'executive', 'committee', ',', 'which', 'had', 'over-all', 'charge', 'of', 'the', 'election', ',', '``', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'city', 'of', 'atlanta', '``', 'for', 'the', 'manner', 'in', 'which', 'the', 'election', 'was', 'conducted', '.']
Cleaned  : ['jury', 'said', 'presentments', 'city', 'executive', 'committee', 'charge', 'election', 'deserves', 'praise', 'thanks', 'city', 'atlanta', 'manner', 'election', 'conducted']

Sentence 3
Lowercase: ['the', 'september-october', 'term', 'jury', 'had', 'been', 'charged', 'by', 'fulton', 'superior', 'court', 'judge', 'durwood', 'pye', 'to', 'investigate', 'reports', 'of', 'possible', '``', 'irregularities', '``', 'in', 'the', 'hard-fought', 'primary', 'which', 'was', 'won', 'by', 'mayor-nominate', 'ivan', 'allen', 'jr.', '.']
Cleaned  : ['term', 'jury', 'charged', 'fulton', 'superior', 'court', 'judge', 'durwood', 'pye', 'investigate', 'reports', 'possible', 'irregularities', 'primary', 'ivan', 'allen']

Sentence 4
Lowercase: ['``', 'only', 'a', 'relative', 'handful', 'of', 'such', 'reports', 'was', 'received', '``', ',', 'the', 'jury', 'said', ',', '``', 'considering', 'the', 'widespread', 'interest', 'in', 'the', 'election', ',', 'the', 'number', 'of', 'voters', 'and', 'the', 'size', 'of', 'this', 'city', '``', '.']
Cleaned  : ['relative', 'handful', 'reports', 'received', 'jury', 'said', 'considering', 'widespread', 'interest', 'election', 'number', 'voters', 'size', 'city']

Sentence 5
Lowercase: ['the', 'jury', 'said', 'it', 'did', 'find', 'that', 'many', 'of', 'georgia', "'s", 'registration', 'and', 'election', 'laws', '``', 'are', 'outmoded', 'or', 'inadequate', 'and', 'often', 'ambiguous', '``', '.']
Cleaned  : ['jury', 'said', 'find', 'many', 'georgia', 'registration', 'election', 'laws', 'outmoded', 'inadequate', 'often', 'ambiguous']

In [5]:
# Q1(e): Display original and cleaned tokens for at least five sentences

comparison_q1 = pd.DataFrame({
    'Sentence No.': range(1, 6),
    'Original Tokens': lower_tokens[:5],
    'Cleaned Tokens': cleaned_tokens[:5]
})

display(comparison_q1)

print("\nQ1 completed successfully.")

,Sentence No.,Original Tokens,Cleaned Tokens
0,1,"[the, fulton, county, grand, jury, said, frida...","[fulton, county, grand, jury, said, friday, in..."
1,2,"[the, jury, further, said, in, term-end, prese...","[jury, said, presentments, city, executive, co..."
2,3,"[the, september-october, term, jury, had, been...","[term, jury, charged, fulton, superior, court,..."
3,4,"[``, only, a, relative, handful, of, such, rep...","[relative, handful, reports, received, jury, s..."
4,5,"[the, jury, said, it, did, find, that, many, o...","[jury, said, find, many, georgia, registration..."

Q1 completed successfully.

In [6]:
# Q2(a): Extract at least 30 alphabetic words from Brown Corpus

brown_words = [
    word.lower()
    for word in brown.words()
    if word.isalpha()
]

# Required words from the question
required_words = [
    'playing',
    'studies',
    'running',
    'better',
    'cars'
]

# Take 30 Brown Corpus words
selected_words = brown_words[:30]

# Add required words
selected_words.extend(required_words)

# Remove duplicates while maintaining order
selected_words = list(dict.fromkeys(selected_words))

print("Total words selected:", len(selected_words))

print("\nSelected Words:")
print(selected_words)

Total words selected: 30

Selected Words:
['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'recent', 'primary', 'election', 'produced', 'no', 'evidence', 'that', 'any', 'irregularities', 'took', 'place', 'further', 'in', 'presentments', 'city', 'playing', 'studies', 'running', 'better', 'cars']

In [7]:
# Q2(b) and Q2(c):
# Apply Porter Stemmer and WordNet Lemmatizer

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Porter stemming
stems = [
    stemmer.stem(word)
    for word in selected_words
]

# POS information for required examples
pos_mapping = {
    'playing': 'v',
    'studies': 'v',
    'running': 'v',
    'better': 'a',
    'cars': 'n'
}

# Lemmatization function
def get_lemma(word):
    return lemmatizer.lemmatize(
        word,
        pos=pos_mapping.get(word, 'n')
    )

lemmas = [
    get_lemma(word)
    for word in selected_words
]

# Create comparison table
comparison_q2 = pd.DataFrame({
    'Original Word': selected_words,
    'Stem': stems,
    'Lemma': lemmas
})

display(comparison_q2)

     Original Word       Stem          Lemma
0              the        the            the
1           fulton     fulton         fulton
2           county     counti         county
3            grand      grand          grand
4             jury       juri           jury
5             said       said           said
6           friday     friday         friday
7               an         an             an
8    investigation   investig  investigation
9               of         of             of
10          recent     recent         recent
11         primary    primari        primary
12        election      elect       election
13        produced     produc       produced
14              no         no             no
15        evidence       evid       evidence
16            that       that           that
17             any        ani            any
18  irregularities  irregular   irregularity
19            took       took           took
20           place      place          place
21         further    further        further
22              in         in             in
23    presentments    present    presentment
24            city       citi           city
25         playing       play           play
26         studies      studi          study
27         running        run            run
28          better     better           good
29            cars        car            car

In [8]:
# Q2(d): Check required words
# playing, studies, running, better and cars

print("Required Example Words:\n")

required_comparison = comparison_q2[
    comparison_q2['Original Word'].isin(required_words)
]

display(required_comparison)

print("\nObservation:")
print("Stemming removes word endings mechanically,")
print("while lemmatization converts words to meaningful dictionary forms.")

Required Example Words:

   Original Word    Stem  Lemma
25       playing    play   play
26       studies   studi  study
27       running     run    run
28        better  better   good
29          cars     car    car

Observation:
Stemming removes word endings mechanically,
while lemmatization converts words to meaningful dictionary forms.

In [9]:
# Q3(a): Load NLTK Words Corpus

vocabulary = sorted({
    word.lower()
    for word in words.words()
    if word.isalpha()
})

print("Total vocabulary words:", len(vocabulary))

# Q3(b): Create at least 10 intentionally misspelled words

misspelled_words = [
    'recieve',
    'definately',
    'seperate',
    'occured',
    'enviroment',
    'becuase',
    'wierd',
    'adress',
    'tommorow',
    'goverment'
]

print("\nIntentionally Misspelled Words:")

for word in misspelled_words:
    print(word)

Total vocabulary words: 234375

Intentionally Misspelled Words:
recieve
definately
seperate
occured
enviroment
becuase
wierd
adress
tommorow
goverment

In [10]:
# Q3(c): Use approximate string matching

def suggest_correction(word, cutoff=0.60):
    """
    Find the closest word from the NLTK Words Corpus.
    """
    matches = get_close_matches(
        word.lower(),
        vocabulary,
        n=1,
        cutoff=cutoff
    )
    
    return matches[0] if matches else "No suggestion"


# Generate corrections
suggestions = [
    suggest_correction(word)
    for word in misspelled_words
]

# Q3(d): Display misspelled words and suggestions

spelling_df = pd.DataFrame({
    'Misspelled Word': misspelled_words,
    'Suggested Correction': suggestions
})

display(spelling_df)

  Misspelled Word Suggested Correction
0         recieve            reachieve
1      definately           definitely
2        seperate              sperate
3         occured                occur
4      enviroment          environment
5         becuase              bedcase
6           wierd                 wird
7          adress              adpress
8        tommorow             tomorrow
9       goverment           government

In [11]:
# Q3(e): Correct at least five example sentences

example_sentences = [
    "I definately want to visit the museum tommorow.",
    "She recieved the adress yesterday.",
    "The enviroment is very important for everyone.",
    "He seperated the papers becuase they were mixed.",
    "The goverment made a wierd decision."
]


def correct_sentence(sentence):
    """
    Correct misspelled alphabetic words
    while keeping punctuation.
    """
    
    tokens = re.findall(
        r"[A-Za-z]+|[^A-Za-z\s]",
        sentence
    )
    
    corrected_tokens = []
    
    for token in tokens:
        
        if token.isalpha():
            lower_token = token.lower()
            
            # Check whether the word exists
            if lower_token not in vocabulary:
                
                suggestion = suggest_correction(
                    lower_token
                )
                
                if suggestion != "No suggestion":
                    
                    # Preserve first-letter capitalization
                    if token[0].isupper():
                        suggestion = suggestion.capitalize()
                    
                    token = suggestion
        
        corrected_tokens.append(token)
    
    # Reconstruct sentence
    result = ""
    
    for token in corrected_tokens:
        
        if token in string.punctuation:
            result += token
            
        else:
            if result:
                result += " "
            
            result += token
    
    return result


# Correct all sentences
corrected_sentences = [
    correct_sentence(sentence)
    for sentence in example_sentences
]


# Display results
print("SPELLING CORRECTION OF SENTENCES")
print("=" * 70)

for i, (original, corrected) in enumerate(
    zip(example_sentences, corrected_sentences),
    1
):
    
    print(f"\nSentence {i}")
    print("Original :", original)
    print("Corrected:", corrected)

print("\nQ3 completed successfully.")

SPELLING CORRECTION OF SENTENCES
======================================================================

Sentence 1
Original : I definately want to visit the museum tommorow.
Corrected: I definitely want to visit the museum tomorrow.

Sentence 2
Original : She recieved the adress yesterday.
Corrected: She relieved the adpress yesterday.

Sentence 3
Original : The enviroment is very important for everyone.
Corrected: The environment is very important for everyone.

Sentence 4
Original : He seperated the papers becuase they were mixed.
Corrected: He sperate the paper bedcase they were mixed.

Sentence 5
Original : The goverment made a wierd decision.
Corrected: The government made a wird decision.

Q3 completed successfully.

In [12]:
# ============================================================
# Q4: UNIGRAM, BIGRAM AND TRIGRAM ANALYSIS
# ============================================================

# Q4(a): Load a suitable subset of Brown Corpus
brown_subset = brown.words()[:5000]

# Q4(b): Retain lowercase alphabetic tokens
preprocessed_tokens = [
    word.lower()
    for word in brown_subset
    if word.isalpha()
]

print("Number of original words:", len(brown_subset))
print("Number of preprocessed tokens:", len(preprocessed_tokens))

print("\nFirst 50 Preprocessed Tokens:")
print(preprocessed_tokens[:50])


# Q4(c): Generate N-grams

unigrams = list(ngrams(preprocessed_tokens, 1))
bigrams = list(ngrams(preprocessed_tokens, 2))
trigrams = list(ngrams(preprocessed_tokens, 3))


print("\nFirst 10 Unigrams:")
print(unigrams[:10])

print("\nFirst 10 Bigrams:")
print(bigrams[:10])

print("\nFirst 10 Trigrams:")
print(trigrams[:10])


# Q4(d): Calculate N-gram frequencies

unigram_freq = FreqDist(unigrams)
bigram_freq = FreqDist(bigrams)
trigram_freq = FreqDist(trigrams)


print("\nUnique Unigrams:", len(unigram_freq))
print("Unique Bigrams :", len(bigram_freq))
print("Unique Trigrams:", len(trigram_freq))

Number of original words: 5000
Number of preprocessed tokens: 4202

First 50 Preprocessed Tokens:
['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'recent', 'primary', 'election', 'produced', 'no', 'evidence', 'that', 'any', 'irregularities', 'took', 'place', 'the', 'jury', 'further', 'said', 'in', 'presentments', 'that', 'the', 'city', 'executive', 'committee', 'which', 'had', 'charge', 'of', 'the', 'election', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'city', 'of', 'atlanta', 'for', 'the']

First 10 Unigrams:
[('the',), ('fulton',), ('county',), ('grand',), ('jury',), ('said',), ('friday',), ('an',), ('investigation',), ('of',)]

First 10 Bigrams:
[('the', 'fulton'), ('fulton', 'county'), ('county', 'grand'), ('grand', 'jury'), ('jury', 'said'), ('said', 'friday'), ('friday', 'an'), ('an', 'investigation'), ('investigation', 'of'), ('of', 'recent')]

First 10 Trigrams:
[('the', 'fulton', 'county'), ('fulton', 'county', 'grand'), ('county', 'grand', 'jury'), ('grand', 'jury', 'said'), ('jury', 'said', 'friday'), ('said', 'friday', 'an'), ('friday', 'an', 'investigation'), ('an', 'investigation', 'of'), ('investigation', 'of', 'recent'), ('of', 'recent', 'primary')]

Unique Unigrams: 1383
Unique Bigrams : 3491
Unique Trigrams: 4075

In [13]:
# Q4(e): Display ten most frequent unigrams, bigrams and trigrams

# Top 10 unigrams
top_unigrams = pd.DataFrame(
    [
        (gram[0], frequency)
        for gram, frequency in unigram_freq.most_common(10)
    ],
    columns=['Unigram', 'Frequency']
)


# Top 10 bigrams
top_bigrams = pd.DataFrame(
    [
        (' '.join(gram), frequency)
        for gram, frequency in bigram_freq.most_common(10)
    ],
    columns=['Bigram', 'Frequency']
)


# Top 10 trigrams
top_trigrams = pd.DataFrame(
    [
        (' '.join(gram), frequency)
        for gram, frequency in trigram_freq.most_common(10)
    ],
    columns=['Trigram', 'Frequency']
)


print("=" * 70)
print("TOP 10 MOST FREQUENT UNIGRAMS")
print("=" * 70)
display(top_unigrams)


print("=" * 70)
print("TOP 10 MOST FREQUENT BIGRAMS")
print("=" * 70)
display(top_bigrams)


print("=" * 70)
print("TOP 10 MOST FREQUENT TRIGRAMS")
print("=" * 70)
display(top_trigrams)

======================================================================
TOP 10 MOST FREQUENT UNIGRAMS
======================================================================

  Unigram  Frequency
0     the        326
1      of        172
2      to        124
3       a        111
4      in         82
5     and         82
6     for         47
7    that         42
8    said         41
9      by         37

======================================================================
TOP 10 MOST FREQUENT BIGRAMS
======================================================================

      Bigram  Frequency
0     of the         44
1     in the         35
2     on the         15
3   the jury         14
4  the state         14
5     to the         13
6    for the         12
7     at the         10
8   the bill         10
9   that the          9

======================================================================
TOP 10 MOST FREQUENT TRIGRAMS
======================================================================

             Trigram  Frequency
0      the jury said          7
1     is expected to          4
2        some of the          4
3  the fulton county          3
4       jury said it          3
5       in the state          3
6        to make the          3
7      would have to          3
8   million worth of          3
9       to the state          3

In [ ]:
# Q4(f) Effect of Increasing N in N-grams

An N-gram is a sequence of N consecutive words.

### Unigram

A unigram contains only one word.

Example:

`machine`

It provides very little contextual information.

### Bigram

A bigram contains two consecutive words.

Example:

`machine learning`

It provides more information about the relationship between words.

### Trigram

A trigram contains three consecutive words.

Example:

`machine learning model`

It captures more contextual and word-order information.

### Effect of Increasing N

As N increases, the N-gram captures more context.

Therefore:

**Unigram → Less context**

**Bigram → More context**

**Trigram → Even more context**

However, increasing N also increases the number of possible word combinations. Higher-order N-grams occur less frequently, which can cause **data sparsity**.

Therefore, there is a trade-off between:

- More contextual information
- More data requirements
- Higher computational complexity
- Data sparsity

For this reason, the appropriate value of N depends on the application and the amount of available training data.